### ISSUE TITLE
Overly-tight Kerning

### ISSUE THREAD

**Issue by aaronbell** [fontworks-fonts/RocknRoll#2]
In reviewing the kerning data, we found that there are some of the new kerning pairs that are super tight: 
![128332693-8398c4a9-99ff-4c6e-ab99-39b06048dec4](https://user-images.githubusercontent.com/8460297/128744196-ad92185d-b02c-4001-8029-be56d687b519.gif)

Can you review the kerning data for the above pairs (and in general)?

**Comment by kokiabe** [comment]
@aaronbell   You’re right. So I reviewed and readjusted all the kerning pairs.
Could you try from the  [`adjust_kerning`](https://github.com/fontworks-fonts/RocknRoll/tree/adjust_kerning) branch and see if that fixes it?

**Comment by aaronbell** [comment]
Looks better! I've pushed an update that adds the GASP table in. Cheers
